/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author deleo
 */
public class frm_listado_factura extends javax.swing.JFrame {

    /**
     * Creates new form frm_factura
     */
    public frm_listado_factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_listado_factura = new javax.swing.JPanel();
        lbl_facturacion = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lbl_tel = new javax.swing.JLabel();
        lbl_detalle = new javax.swing.JLabel();
        btn_vaciar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        tabla_factura = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de facturas");
        setBackground(new java.awt.Color(204, 255, 255));

        panel_listado_factura.setBackground(new java.awt.Color(255, 255, 255));
        panel_listado_factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_facturacion.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_facturacion.setForeground(new java.awt.Color(94, 141, 147));
        lbl_facturacion.setText("Factura");
        panel_listado_factura.add(lbl_facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));
        panel_listado_factura.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 132, -1));

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        panel_listado_factura.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 129, -1));

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(81, 124, 164));
        lbl_nombre.setText("Nombre");
        panel_listado_factura.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        lbl_cedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_cedula.setForeground(new java.awt.Color(81, 124, 164));
        lbl_cedula.setText("Cedula");
        panel_listado_factura.add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));
        panel_listado_factura.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 126, -1));

        lbl_tel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tel.setForeground(new java.awt.Color(81, 124, 164));
        lbl_tel.setText("Telefono");
        panel_listado_factura.add(lbl_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        lbl_detalle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_detalle.setForeground(new java.awt.Color(81, 124, 164));
        lbl_detalle.setText("Detalle:");
        panel_listado_factura.add(lbl_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btn_vaciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-32.png"))); // NOI18N
        btn_vaciar.setToolTipText("Vaciar");
        btn_vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarActionPerformed(evt);
            }
        });
        panel_listado_factura.add(btn_vaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 131, 30, 30));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir ");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_listado_factura.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-búsqueda-32.png"))); // NOI18N
        btn_buscar.setToolTipText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        panel_listado_factura.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-imprimir-32.png"))); // NOI18N
        btn_imprimir.setToolTipText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        panel_listado_factura.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", " ", "", ""
            }
        ));
        tabla_factura.setViewportView(jTable1);

        panel_listado_factura.add(tabla_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 690, 240));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_listado_factura.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_listado_factura, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_listado_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
        // Este es el texfield de la cedula del paciente desde aqui lo podemos modificar
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void btn_vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarActionPerformed
        // Este es el boton que permite vaciar todos los text field que esten llenos 
        
        
        
    }//GEN-LAST:event_btn_vaciarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Este es el boton que permite salir a menu de los listado
         frm_listas mf = new frm_listas();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
       //        Este es el boton que permite imprimir el listado de las facturas 
//  Aqui definimos una variable que se llama outfile y esta es igual al lugar donde tenemos el archivo que queremos mostrar
           String outFile = "C:\\Users\\jim3j\\OneDrive\\Documentos\\NetBeansProjects\\Dental_Friends\\src\\Reportes\\factura.pdf";
        
        Connection cn=MyConnetion.getConnection(); // definimos una nueva conexion y le ponemos el nombre de cn 
        try{
          JasperReport jr = (JasperReport) JRLoader.loadObject(frm_paciente_listado.class.getResource("/Reportes/factura.jasper"));
           // creamos un nuevo jasper report y ejecutamos una libreria que nos perimite cargar un reporte de jasper ya guardado en una carpeta
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte Factura");
            
          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true);          
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            // usamos este catch para que muestre cualquier error que tenga la impresion del codigo
}

    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        //        Este es el boton que permite buscar cualquier empleado que este registrado en la base de datos
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listado_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listado_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listado_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listado_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listado_factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_vaciar;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_detalle;
    private javax.swing.JLabel lbl_facturacion;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JPanel panel_listado_factura;
    private javax.swing.JScrollPane tabla_factura;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
