/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Alian Peralta
 */
public class frm_producto extends javax.swing.JFrame {

    /**
     * Creates new form frm_producto
     */
    public frm_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_producto = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombre_product = new javax.swing.JLabel();
        txt_nombre_product = new javax.swing.JTextField();
        lbl_lote = new javax.swing.JLabel();
        txt_lote = new javax.swing.JTextField();
        txt_fecha_vencimiento = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        lbl_fecha_vencimiento = new javax.swing.JLabel();
        lbl_representacion = new javax.swing.JLabel();
        txt_coste = new javax.swing.JTextField();
        lbl_coste = new javax.swing.JLabel();
        cmb_representacion = new javax.swing.JComboBox<>();
        btn_produ = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_producto.setBackground(new java.awt.Color(255, 255, 255));
        panel_producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(94, 141, 147));
        lbl_titulo.setText("Registro de producto ");
        panel_producto.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_nombre_product.setBackground(java.awt.Color.white);
        lbl_nombre_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_nombre_product.setForeground(new java.awt.Color(81, 124, 164));
        lbl_nombre_product.setText("Nombre:");
        panel_producto.add(lbl_nombre_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txt_nombre_product.setForeground(new java.awt.Color(240, 240, 240));
        panel_producto.add(txt_nombre_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));

        lbl_lote.setBackground(java.awt.Color.white);
        lbl_lote.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_lote.setForeground(new java.awt.Color(81, 124, 164));
        lbl_lote.setText("Lote:");
        panel_producto.add(lbl_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        txt_lote.setForeground(new java.awt.Color(240, 240, 240));
        panel_producto.add(txt_lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, -1));

        txt_fecha_vencimiento.setForeground(new java.awt.Color(240, 240, 240));
        panel_producto.add(txt_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        lbl_marca.setBackground(java.awt.Color.white);
        lbl_marca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(81, 124, 164));
        lbl_marca.setText("Marca:");
        panel_producto.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_fecha_vencimiento.setBackground(java.awt.Color.white);
        lbl_fecha_vencimiento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_fecha_vencimiento.setForeground(new java.awt.Color(81, 124, 164));
        lbl_fecha_vencimiento.setText("Fecha vencimiento:");
        panel_producto.add(lbl_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lbl_representacion.setBackground(java.awt.Color.white);
        lbl_representacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_representacion.setForeground(new java.awt.Color(81, 124, 164));
        lbl_representacion.setText("Representacion:");
        panel_producto.add(lbl_representacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txt_coste.setForeground(new java.awt.Color(240, 240, 240));
        panel_producto.add(txt_coste, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, -1));

        lbl_coste.setBackground(java.awt.Color.white);
        lbl_coste.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_coste.setForeground(new java.awt.Color(81, 124, 164));
        lbl_coste.setText("Coste mercado");
        panel_producto.add(lbl_coste, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 20));

        cmb_representacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_representacion.setForeground(new java.awt.Color(94, 141, 147));
        cmb_representacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Liquido", "Solido", "Polvo" }));
        panel_producto.add(cmb_representacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 154, -1));

        btn_produ.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_produ.setForeground(new java.awt.Color(94, 141, 147));
        btn_produ.setText("Registrar");
        btn_produ.setToolTipText("");
        btn_produ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_produ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produActionPerformed(evt);
            }
        });
        panel_producto.add(btn_produ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 130, 60));

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_producto.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txt_marca.setForeground(new java.awt.Color(240, 240, 240));
        panel_producto.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir al menu principal");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_producto.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 70, 60));

        getContentPane().add(panel_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produActionPerformed
         // Este es el boton que permite registrar un paciente:
        JOptionPane.showMessageDialog(null,"Has registrado un producto correctamente");
    }//GEN-LAST:event_btn_produActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
      // Este es el boton que permite salir al menu principal o el main
        frm_main mf = new frm_main(); // aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_produ;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cmb_representacion;
    private javax.swing.JLabel lbl_coste;
    private javax.swing.JLabel lbl_fecha_vencimiento;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_lote;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_nombre_product;
    private javax.swing.JLabel lbl_representacion;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel panel_producto;
    private javax.swing.JTextField txt_coste;
    private javax.swing.JTextField txt_fecha_vencimiento;
    private javax.swing.JTextField txt_lote;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_nombre_product;
    // End of variables declaration//GEN-END:variables
}
