/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Alian Peralta
 */
public class frm_paciente extends javax.swing.JFrame {

    /**
     * Creates new form frm_cliente
     */
    public frm_paciente() {
        initComponents();
    }
    public boolean RevisarPaciente(String usuario){
          PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `paciente` WHERE `nombre` =?";
        try {
            ps = MyConnetion.getConnection().prepareStatement(query);
            ps.setString(1, usuario);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        }   catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        return checkUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_paciente = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_cedu = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        lbl_dire = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_correo = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        lbl_tel = new javax.swing.JLabel();
        lbl_ape = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_core = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_regipaciente1 = new javax.swing.JButton();
        scrpanel_tabla = new javax.swing.JScrollPane();
        tabla_paciente = new javax.swing.JTable();
        sp_separador = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de pacientes");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_paciente.setBackground(new java.awt.Color(255, 255, 255));
        panel_paciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(81, 124, 164));
        lbl_nombre.setText("Nombre:");
        panel_paciente.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txt_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        panel_paciente.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 137, 20));

        lbl_cedu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_cedu.setForeground(new java.awt.Color(81, 124, 164));
        lbl_cedu.setText("Cedula:");
        panel_paciente.add(lbl_cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txt_cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        panel_paciente.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 150, 20));

        lbl_dire.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_dire.setForeground(new java.awt.Color(81, 124, 164));
        lbl_dire.setText("Direccion:");
        panel_paciente.add(lbl_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txt_direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        panel_paciente.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 130, 20));

        lbl_correo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_correo.setForeground(new java.awt.Color(81, 124, 164));
        lbl_correo.setText("Correo:");
        panel_paciente.add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(94, 141, 147));
        btn_editar.setText("Editar");
        btn_editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        panel_paciente.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, 40));

        lbl_tel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_tel.setForeground(new java.awt.Color(81, 124, 164));
        lbl_tel.setText("Telefono:");
        panel_paciente.add(lbl_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        lbl_ape.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_ape.setForeground(new java.awt.Color(81, 124, 164));
        lbl_ape.setText("Apellido:");
        panel_paciente.add(lbl_ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        txt_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        panel_paciente.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 147, 20));

        txt_telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        panel_paciente.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 147, 20));

        txt_core.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147)));
        panel_paciente.add(txt_core, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 147, 20));

        lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(94, 141, 147));
        lbl_title.setText("Registro de paciente");
        panel_paciente.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_paciente.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir al menu principal");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_paciente.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        btn_regipaciente1.setBackground(new java.awt.Color(255, 255, 255));
        btn_regipaciente1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_regipaciente1.setForeground(new java.awt.Color(94, 141, 147));
        btn_regipaciente1.setText("Registrar");
        btn_regipaciente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_regipaciente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regipaciente1ActionPerformed(evt);
            }
        });
        panel_paciente.add(btn_regipaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 100, 40));

        getContentPane().add(panel_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 430));

        tabla_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        scrpanel_tabla.setViewportView(tabla_paciente);

        getContentPane().add(scrpanel_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 400));
        getContentPane().add(sp_separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 2, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
      // Este es el boton que permite registrar un paciente:
    
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
       // Este es el texfield del apellido del paciente desde aqui lo podemos modificar
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
         // Este es el boton que permite salir al menu principal o el main
        frm_main mf = new frm_main(); // aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_regipaciente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regipaciente1ActionPerformed

        // Este boton para permite registrar pacientes nuevos a la BD
  
        String nom = txt_nombre.getText();
        String ape = txt_apellido.getText();
              String ced = txt_cedula.getText();
        String dir = txt_direccion.getText();
         String tel = txt_telefono.getText();

                
        if(ced.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega un cedula");
        }
        
        else if(nom.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega el nombre");
        }      
        else{
        PreparedStatement ps;
        String query = "INSERT INTO `paciente`(`id_paciente`,`nombre`, `apellido`, `direccion`, `telefono`, `cedula`) VALUES (0,?,?,?,?,?)";
        try {
            ps = MyConnetion.getConnection().prepareStatement(query);
            
            ps.setString(1, nom);
            ps.setString(2, ape);
             ps.setString(3, dir);
             ps.setString(4, tel);          
             ps.setString(5, ced);
        
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Nuevo paciente Agregado");
//                Limpiar();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
       }
        
    }//GEN-LAST:event_btn_regipaciente1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_regipaciente1;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_ape;
    private javax.swing.JLabel lbl_cedu;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_dire;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_paciente;
    private javax.swing.JScrollPane scrpanel_tabla;
    private javax.swing.JSeparator sp_separador;
    private javax.swing.JTable tabla_paciente;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_core;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
