/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author deleo
 */
public class frm_listado_productos extends javax.swing.JFrame {
DefaultTableModel model = new DefaultTableModel();


    /**
     * Creates new form frm_inventario
     */
    public frm_listado_productos() {
        initComponents();
        MostrarProducto("");
    }
    
    public void RefrescarTabla(){ 
        try{
            model.setColumnCount(0); 
            model.setRowCount(0); 
            tabla_produc.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error" + ex);
        }
    
    }
    
    public void MostrarProducto (String producto){
          
        String sql = "" +  producto; 
        Statement st;
        MyConnetion cc = new MyConnetion();
        Connection cn = MyConnetion.getConnection();
        RefrescarTabla();
        model.addColumn("ID");  
        model.addColumn("Nombre");
        model.addColumn("Categoria");
        model.addColumn("Marca");
        model.addColumn("Descripcion");
        model.addColumn("Precio");
        model.addColumn("Fecha vencimiento");
        model.addColumn("ID del producto");
        model.addColumn("ID del admin");
        
        tabla_produc.setModel(model); 
      
        String [] dato = new String[9];
          if(producto.equals("")){ 
          sql = "Select * from `producto`"; 
        }
          else {
          sql = "select * from `producto` where `id_product` = '" + txt_id.getText()+ "'"+ " or nombre = '" + txt_nombre.getText()+ "'" + "or marca = '" + txt_marca.getText() +"'";
          }
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql); 
            while(rs.next()) 
            {  

            dato[0] =rs.getString(1);
            dato[1] =rs.getString(2);
            dato[2] =rs.getString(3);
            dato[3] =rs.getString(4);
            dato[4] =rs.getString(5);
            dato[5] =rs.getString(6);
            dato[6] =rs.getString(7);
            dato[7] =rs.getString(8);
            dato[8] =rs.getString(9);

            model.addRow(dato);
            txt_id.setText(rs.getString("id_product"));
            txt_nombre.setText(rs.getString("nombre"));
            txt_marca.setText(rs.getString("marca"));
            }
        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error" + e);
        }
    }
    
     public void Limpiar(){  
         txt_id.setText("");
         txt_nombre.setText("");
         txt_marca.setText("");
     }

    public void EliminarProducto(String id) {
        String sql = "delete from producto where id_product = " + id;
        Statement st;
        Connection cn = MyConnetion.getConnection();
        try {
            st = cn.createStatement();
            int rs = st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error" + e);
        }
    }
    
    
    
    

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_listado_producto = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_produc = new javax.swing.JTable();
        lbl_descripcion = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        btn_vaciar = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_listado_producto.setBackground(new java.awt.Color(255, 255, 255));
        panel_listado_producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(94, 141, 147));
        lbl_title.setText("Listados de Productos");
        panel_listado_producto.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        tabla_produc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        tabla_produc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_produc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_producMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_produc);

        panel_listado_producto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 703, 170));

        lbl_descripcion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_descripcion.setForeground(new java.awt.Color(94, 141, 147));
        lbl_descripcion.setText("Descripción:");
        panel_listado_producto.add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_listado_producto.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 41, 41));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-búsqueda-32.png"))); // NOI18N
        btn_buscar.setToolTipText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        panel_listado_producto.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 50, -1));

        btn_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-imprimir-32.png"))); // NOI18N
        btn_imprimir.setToolTipText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        panel_listado_producto.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 45, -1));
        panel_listado_producto.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 132, -1));
        panel_listado_producto.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 129, -1));

        lbl_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(81, 124, 164));
        lbl_id.setText("Id:");
        panel_listado_producto.add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(81, 124, 164));
        lbl_nombre.setText("Nombre:");
        panel_listado_producto.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        panel_listado_producto.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 126, -1));

        lbl_marca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(81, 124, 164));
        lbl_marca.setText("Marca:");
        panel_listado_producto.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        btn_vaciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-empty-48.png"))); // NOI18N
        btn_vaciar.setToolTipText("Vaciar");
        btn_vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciarActionPerformed(evt);
            }
        });
        panel_listado_producto.add(btn_vaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 60, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_listado_producto.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-eliminar-32.png"))); // NOI18N
        btn_eliminar.setToolTipText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        panel_listado_producto.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        getContentPane().add(panel_listado_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Este es el boton que permite salir a menu de los listado
        frm_listas mf = new frm_listas();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        //        Este es el boton que permite imprimir el listado de las productos 
//  Aqui definimos una variable que se llama outfile y esta es igual al lugar donde tenemos el archivo que queremos mostrar
       String outFile = "C:\\Users\\jim3j\\OneDrive\\Documentos\\NetBeansProjects\\Dental_Friends\\src\\Reportes\\producto.pdf";
        
       Connection cn=MyConnetion.getConnection(); // definimos una nueva conexion y le ponemos el nombre de cn 
       try{
       JasperReport jr = (JasperReport) JRLoader.loadObject(frm_paciente_listado.class.getResource("/Reportes/producto.jasper"));
           // creamos un nuevo jasper report y ejecutamos una libreria que nos perimite cargar un reporte de jasper ya guardado en una carpeta
       Map parametros = new HashMap<>();
       parametros.put("Titulo", "Reporte producto");
            
       JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
       JasperViewer jv = new JasperViewer(jp, false);
       jv.setVisible(true);          
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);  // usamos este catch para que muestre cualquier error que tenga la impresion del codigo
}

    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciarActionPerformed
          // Este es el boton que permite vaciar todos los text field que esten llenos 
               
          Limpiar();

    }//GEN-LAST:event_btn_vaciarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // Este es un boton que funcina para buscar un producto en especifico
        
        MostrarProducto("Producto");
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // este boton funciona para eliminar un producto
        String id = tabla_produc.getValueAt(tabla_produc.getSelectedRow(), 0).toString();     
        EliminarProducto(id); // llamamos nuestro metodo para eliminar
        MostrarProducto("");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void tabla_producMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_producMouseClicked
       // Este es un evento que al momento de darle click a una producto se rellenen todos los texfields con los datos de esta
    txt_id.setText(tabla_produc.getValueAt(tabla_produc.getSelectedRow(), 0).toString());
    txt_marca.setText(tabla_produc.getValueAt(tabla_produc.getSelectedRow(), 3).toString());
    txt_nombre.setText(tabla_produc.getValueAt(tabla_produc.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tabla_producMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listado_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listado_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listado_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listado_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listado_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_vaciar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_listado_producto;
    private javax.swing.JTable tabla_produc;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
