/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alian Peralta
 */
public class frm_producto extends javax.swing.JFrame {

    /**
     * Creates new form frm_producto
     */
    public frm_producto() {
        initComponents();
        
        
        
    }
    
    public boolean RevisarPaciente(String producto){
          PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `producto` WHERE `id_product` =?";
        try {
            ps = MyConnetion.getConnection().prepareStatement(query);
            ps.setString(1, producto);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        }   catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        return checkUser;
    }
    
    public void Limpiar(){
    try{
    txt_nombre_product.setText("");
    txt_Categoria.setText("");
    txt_marca.setText("");
    txt_fecha_vencimiento.setText("");
    txt_Descripcion.setText("");
    txt_Precio.setText("");
    txt_Id_proveedor.setText("");
    txt_Id_Admin.setText("");
    
    
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null,"error"+ ex);
    }
}
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_producto = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombre_product = new javax.swing.JLabel();
        txt_nombre_product = new javax.swing.JTextField();
        lbl_Categoria = new javax.swing.JLabel();
        txt_Categoria = new javax.swing.JTextField();
        txt_fecha_vencimiento = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        lbl_fecha_vencimiento = new javax.swing.JLabel();
        lbl_representacion = new javax.swing.JLabel();
        txt_Id_proveedor = new javax.swing.JTextField();
        lbl_Id_Admin = new javax.swing.JLabel();
        btn_produ = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        txt_Descripcion = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        lbl_Precio = new javax.swing.JLabel();
        lbl_Id_proveedor = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JTextField();
        txt_Id_Admin = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_producto.setBackground(new java.awt.Color(255, 255, 255));
        panel_producto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(94, 141, 147));
        lbl_titulo.setText("Registro de producto ");
        panel_producto.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_nombre_product.setBackground(java.awt.Color.white);
        lbl_nombre_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_nombre_product.setForeground(new java.awt.Color(81, 124, 164));
        lbl_nombre_product.setText("Nombre:");
        panel_producto.add(lbl_nombre_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        panel_producto.add(txt_nombre_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));

        lbl_Categoria.setBackground(java.awt.Color.white);
        lbl_Categoria.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Categoria.setForeground(new java.awt.Color(81, 124, 164));
        lbl_Categoria.setText("Categoria:");
        panel_producto.add(lbl_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        panel_producto.add(txt_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, -1));
        panel_producto.add(txt_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        lbl_marca.setBackground(java.awt.Color.white);
        lbl_marca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_marca.setForeground(new java.awt.Color(81, 124, 164));
        lbl_marca.setText("Marca:");
        panel_producto.add(lbl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbl_fecha_vencimiento.setBackground(java.awt.Color.white);
        lbl_fecha_vencimiento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_fecha_vencimiento.setForeground(new java.awt.Color(81, 124, 164));
        lbl_fecha_vencimiento.setText("Fecha vencimiento:");
        panel_producto.add(lbl_fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lbl_representacion.setBackground(java.awt.Color.white);
        lbl_representacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_representacion.setForeground(new java.awt.Color(81, 124, 164));
        lbl_representacion.setText("Descripción:");
        panel_producto.add(lbl_representacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        panel_producto.add(txt_Id_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 150, 20));

        lbl_Id_Admin.setBackground(java.awt.Color.white);
        lbl_Id_Admin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Id_Admin.setForeground(new java.awt.Color(81, 124, 164));
        lbl_Id_Admin.setText("Id_Admin:");
        panel_producto.add(lbl_Id_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, 20));

        btn_produ.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_produ.setForeground(new java.awt.Color(94, 141, 147));
        btn_produ.setText("Registrar");
        btn_produ.setToolTipText("");
        btn_produ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produActionPerformed(evt);
            }
        });
        panel_producto.add(btn_produ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 130, 60));

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_producto.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        panel_producto.add(txt_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 150, -1));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir al menu principal");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_producto.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 70, 60));

        lbl_Precio.setBackground(java.awt.Color.white);
        lbl_Precio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Precio.setForeground(new java.awt.Color(81, 124, 164));
        lbl_Precio.setText("Precio");
        panel_producto.add(lbl_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, 20));

        lbl_Id_proveedor.setBackground(java.awt.Color.white);
        lbl_Id_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_Id_proveedor.setForeground(new java.awt.Color(81, 124, 164));
        lbl_Id_proveedor.setText("Id_proveedor:");
        panel_producto.add(lbl_Id_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 20));
        panel_producto.add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, -1));
        panel_producto.add(txt_Id_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, -1));
        panel_producto.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        getContentPane().add(panel_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produActionPerformed
    // Este boton permite registrar un producto:
        
         
        String nom = txt_nombre_product.getText();
        String categ = txt_Categoria.getText();
        String marca = txt_marca.getText();
        String fecha = txt_fecha_vencimiento.getText();
        String desc = txt_Descripcion.getText();
        String precio = txt_Precio.getText();
        String prove = txt_Id_proveedor.getText();
        String admin = txt_Id_Admin.getText();

        if(admin.equals(""))
        {
            JOptionPane.showMessageDialog(null, "agrega el id_admin ");
        }

        else if(nom.equals(""))
           {
            JOptionPane.showMessageDialog(null, "Agrega el nombre del producto");
           }      
        else{
            PreparedStatement ps;
            String query = "INSERT INTO `producto`(`nombre`, `categoria`, `marca`, `descripcion`,`precio`,`fecha_vencimiento`,`id_proveedor`,`id_admin`) VALUES ( ?,?,?,?,?,?,?,?)";
        try {
        ps = MyConnetion.getConnection().prepareStatement(query);
        
        ps.setString(1, nom);
        ps.setString(2, categ);
        ps.setString(3, marca);
         ps.setString(4, desc);
         ps.setString(5, precio);
         ps.setString(6, fecha);
        ps.setString(7, prove);
        ps.setString(8, admin);
    
        if(ps.executeUpdate() > 0)
        {
            JOptionPane.showMessageDialog(null, "Nuevo producto agregado");
            Limpiar();
        }
        
        } catch (SQLException ex) {
        Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error: "+ex);
        }
         
         
         
        }
    }//GEN-LAST:event_btn_produActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
      // Este es el boton que permite salir al menu principal o el main
        frm_main mf = new frm_main(); // aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_produ;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_Categoria;
    private javax.swing.JLabel lbl_Id_Admin;
    private javax.swing.JLabel lbl_Id_proveedor;
    private javax.swing.JLabel lbl_Precio;
    private javax.swing.JLabel lbl_fecha_vencimiento;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_nombre_product;
    private javax.swing.JLabel lbl_representacion;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel panel_producto;
    private javax.swing.JTextField txt_Categoria;
    private javax.swing.JTextField txt_Descripcion;
    private javax.swing.JTextField txt_Id_Admin;
    private javax.swing.JTextField txt_Id_proveedor;
    private javax.swing.JTextField txt_Precio;
    private javax.swing.JTextField txt_fecha_vencimiento;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_nombre_product;
    // End of variables declaration//GEN-END:variables
}
