/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alian Peralta
 */
public class frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        initComponents();
    }
   public boolean RevisarUsuario(String usuario){
        //Funcion para Revisar si el usuario existe dentro de la BD
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `admin` WHERE `nombre` =?";
        try {
            ps = MyConnetion.getConnection().prepareStatement(query);
            ps.setString(1, usuario);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        }   catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        return checkUser;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_panei = new javax.swing.JPanel();
        lbl_inicio = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_clave = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        btn_boton = new javax.swing.JButton();
        lbl_dfdental = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        lbl_df = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        lb_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");

        lbl_panei.setBackground(new java.awt.Color(0, 0, 0));
        lbl_panei.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_inicio.setFont(new java.awt.Font("Magneto", 1, 18)); // NOI18N
        lbl_inicio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio.setText("Inicio de Sesion:");
        lbl_panei.add(lbl_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 157, -1, -1));

        lbl_usuario.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Usuario:");
        lbl_panei.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 187, -1, -1));

        lbl_clave.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        lbl_clave.setForeground(new java.awt.Color(255, 255, 255));
        lbl_clave.setText("Clave:");
        lbl_panei.add(lbl_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 238, -1, -1));

        txt_usuario.setToolTipText("");
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        lbl_panei.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 186, 105, -1));

        btn_boton.setBackground(new java.awt.Color(255, 255, 255));
        btn_boton.setFont(new java.awt.Font("Magneto", 1, 16)); // NOI18N
        btn_boton.setText("inicia");
        btn_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_botonActionPerformed(evt);
            }
        });
        lbl_panei.add(btn_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lbl_dfdental.setFont(new java.awt.Font("Magneto", 0, 36)); // NOI18N
        lbl_dfdental.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dfdental.setText("DF");
        lbl_dfdental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titulo(evt);
            }
        });
        lbl_panei.add(lbl_dfdental, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, -1, -1));

        lbl_ano.setFont(new java.awt.Font("Freestyle Script", 0, 36)); // NOI18N
        lbl_ano.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ano.setText("2022-2023");
        lbl_panei.add(lbl_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 108, -1, -1));

        lbl_df.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        lbl_df.setForeground(new java.awt.Color(255, 255, 255));
        lbl_df.setText("Dental Friends");
        lbl_df.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dental(evt);
            }
        });
        lbl_panei.add(lbl_df, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 62, -1, -1));
        lbl_panei.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 237, 120, -1));

        lb_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sellos.png"))); // NOI18N
        lb_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_imgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_panei, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_panei, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lb_img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        //Este es el texfield del usuario al momento del usuario ingresar algun dato que no queremos en el text field desde aqui lo podemos modificar
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_botonActionPerformed
        // Este es el boton que permite que el usuario ingrese
       PreparedStatement ps;
        ResultSet rs;
        String Usuario, Clave,S;
        Usuario = txt_usuario.getText();
        Clave = String.valueOf(txt_clave.getPassword());
        String query = "SELECT * FROM `admin` WHERE `nombre` =? AND `contraseña` =?";
        
        try{
            ps = MyConnetion.getConnection().prepareStatement(query);
            ps.setString(1, Usuario);
            ps.setString(2, Clave);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
            frm_main mf = new frm_main();
            mf.setVisible(true);
            mf.pack();
            this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario o Clave incorrectos", "Fallo en Acesso",2);
            }
            }   catch (SQLException ex){
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error" + ex);
}
         // Tenemos estas Variables definidas para agregarles un valor en especifico despues
      
         // aqui estamos definiendo que la variable usuario sera igual al texfiel de usuario 
      
        //aqui estamos definiendo que la variable clave sera igual al texfiel de clave 
/** usamos este if else para que solo deje pasar al main a un admin 
 * y esto es porque la condicion del if es que admin es igual a la variable de usuario 
 * y al igual que la variable clave que tambien es igual a admin.
       
        */ 
//if ("admin".equals(Usuario) && "admin".equals(Clave)){
//            JOptionPane.showMessageDialog(null,"Bienvenido " + Usuario); // si la condicion se cumple aparecera este mensaje 
//            frm_main mf = new frm_main(); // aqui estamos creando un mf nuevo
//            mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
//            mf.pack();
//            this.dispose(); 
//        }
//        else {
//            JOptionPane.showMessageDialog(null,"No eres admin muevalo ratrero"); // en caso de que la condicion no se cumpla aparecera este mensaje
//        }

    }//GEN-LAST:event_btn_botonActionPerformed

    private void titulo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo
        // En caso de que toquen el titulo aparecera este mensaje
         JOptionPane.showMessageDialog(null,"Tocaste de el Titulo y este significa DF = Dental Friends");
    }//GEN-LAST:event_titulo

    private void dental(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dental
        // En caso de que toquen estas palabras aparecera este mensaje
        JOptionPane.showMessageDialog(null,"Tocaste Dental Friends");
    }//GEN-LAST:event_dental

    private void lb_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_imgMouseClicked
        // En caso de que toquen el logo aparecera este mensaje
        JOptionPane.showMessageDialog(null,"Tocaste el logo de Dental Friends");
    }//GEN-LAST:event_lb_imgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_boton;
    private javax.swing.JLabel lb_img;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_clave;
    private javax.swing.JLabel lbl_df;
    private javax.swing.JLabel lbl_dfdental;
    private javax.swing.JLabel lbl_inicio;
    private javax.swing.JPanel lbl_panei;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
