/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DF_presentacion;

/**
 *
 * @author jim3j
 */
public class frm_listas extends javax.swing.JFrame {

    /**
     * Creates new form frm_listas
     */
    public frm_listas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_listas = new javax.swing.JPanel();
        btn_paci = new javax.swing.JButton();
        btn_empl = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        lbl_pacientes = new javax.swing.JLabel();
        lbl_empleados = new javax.swing.JLabel();
        lbl_prod = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_fact = new javax.swing.JLabel();
        btn_fact = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main de las listas");

        panel_listas.setBackground(new java.awt.Color(255, 255, 255));
        panel_listas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_paci.setBackground(new java.awt.Color(255, 255, 255));
        btn_paci.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_paci.setForeground(new java.awt.Color(94, 141, 147));
        btn_paci.setText("Listar");
        btn_paci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_paci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paciActionPerformed(evt);
            }
        });
        panel_listas.add(btn_paci, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 50));

        btn_empl.setBackground(new java.awt.Color(255, 255, 255));
        btn_empl.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_empl.setForeground(new java.awt.Color(94, 141, 147));
        btn_empl.setText("Listar");
        btn_empl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_empl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emplActionPerformed(evt);
            }
        });
        panel_listas.add(btn_empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 50));

        btn_producto.setBackground(new java.awt.Color(255, 255, 255));
        btn_producto.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_producto.setForeground(new java.awt.Color(94, 141, 147));
        btn_producto.setText("Listar");
        btn_producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productoActionPerformed(evt);
            }
        });
        panel_listas.add(btn_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 120, 50));

        lbl_pacientes.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_pacientes.setForeground(new java.awt.Color(81, 124, 164));
        lbl_pacientes.setText("Listado de pacientes:");
        panel_listas.add(lbl_pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbl_empleados.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_empleados.setForeground(new java.awt.Color(81, 124, 164));
        lbl_empleados.setText("Listado de empleados:");
        panel_listas.add(lbl_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        lbl_prod.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_prod.setForeground(new java.awt.Color(81, 124, 164));
        lbl_prod.setText("Listado de productos:");
        panel_listas.add(lbl_prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lo.png"))); // NOI18N
        panel_listas.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lbl_fact.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_fact.setForeground(new java.awt.Color(81, 124, 164));
        lbl_fact.setText("Listado de facturas:");
        panel_listas.add(lbl_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 30));

        btn_fact.setBackground(new java.awt.Color(255, 255, 255));
        btn_fact.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_fact.setForeground(new java.awt.Color(94, 141, 147));
        btn_fact.setText("Listar");
        btn_fact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(94, 141, 147), 2));
        btn_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_factActionPerformed(evt);
            }
        });
        panel_listas.add(btn_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 120, 50));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-32.png"))); // NOI18N
        btn_salir.setToolTipText("Salir al menu principal");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel_listas.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_listas, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_listas, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_paciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paciActionPerformed
         // Este es el boton que permite ir a la pantalla de los pancientes listados
        frm_paciente_listado mf = new frm_paciente_listado();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_paciActionPerformed

    private void btn_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productoActionPerformed
        // Este es el boton que permite ir a la pantalla de listado de productos
        frm_listado_productos mf = new frm_listado_productos();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_productoActionPerformed

    private void btn_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_factActionPerformed
       // Este es el boton que permite ir a la pantalla de listado de factura
        frm_listado_factura mf = new frm_listado_factura();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_factActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Este es el boton que permite salir al menu principal o main
        frm_main mf = new frm_main();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_emplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emplActionPerformed
         // Este es el boton que permite ir a la pantalla de listado de empleado
        frm_listado_empleado mf = new frm_listado_empleado();// aqui estamos creando un mf nuevo
        mf.setVisible(true); // esto es para que la pantalla del main pueda ser visible y la otra desaparesca
        mf.pack();
        this.dispose();
    }//GEN-LAST:event_btn_emplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_listas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_empl;
    private javax.swing.JButton btn_fact;
    private javax.swing.JButton btn_paci;
    private javax.swing.JButton btn_producto;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_empleados;
    private javax.swing.JLabel lbl_fact;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_pacientes;
    private javax.swing.JLabel lbl_prod;
    private javax.swing.JPanel panel_listas;
    // End of variables declaration//GEN-END:variables
}
